import { ANALYTICS_EVENTS as __ANALYTICS_EVENTS__ } from "@pkg/analytics";

const DEFAULT_ANALYTICS_EVENTS = {
  CART_ADD: "CART_ADD",
  CART_REMOVE: "CART_REMOVE",
  CART_UPDATE_QUANTITY: "CART_UPDATE_QUANTITY",
  CART_ERROR: "CART_ERROR",
} as const;

export const ANALYTICS_EVENTS =
  __ANALYTICS_EVENTS__ ?? DEFAULT_ANALYTICS_EVENTS;
