export const CAROUSEL_CONFIG = {
  MOBILE_BREAKPOINT: 600,
  WHEEL_DEBOUNCE: 150,
  SWIPE_THRESHOLD: 60,
  SWIPE_VELOCITY_THRESHOLD: 0.3,
  TRANSITION_DURATION: {
    MOBILE: 400,
    DESKTOP: 250,
  },
} as const; 